name: Update WakaTime

on:
  schedule: [{ cron: "0 6 * * 1" }]   # tiap Senin 13:00 WIB kurang-lebih
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_TITLE: true
          TIME_RANGE: last_7_days
          LANG_COUNT: 6
          SHOW_TIME: true
          SHOW_MASKED_TIME: false
